[dev]
   command = "npm run dev"
[build]
  command = "npm run build"
  publish = "dist"
[functions]
  node_bundler = "esbuild"
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[plugins]]
  package = "@netlify/plugin-emails"
